# Generated by Django 6.0.4 on 2026-05-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_tiene_abono_mensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='abono_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimiento del abono'),
        ),
    ]
