# Generated by Django 6.0.4 on 2026-05-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usuario_abono_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clases_a_favor',
            field=models.PositiveIntegerField(default=0, verbose_name='Clases a favor'),
        ),
    ]
