# Generated by Django 6.0.4 on 2026-06-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usuario_clases_a_favor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='clases_a_favor',
        ),
        migrations.AddField(
            model_name='usuario',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo a favor'),
        ),
    ]
