# Generated by Django 6.0.4 on 2026-06-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usuario_clases_a_favor_usuario_saldo_a_favor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo a favor'),
        ),
    ]
