# Generated by Django 6.0.4 on 2026-05-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('mercado_pago', 'Mercado Pago    ')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
