# Generated by Django 6.0.4 on 2026-06-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reembolsado',
            field=models.BooleanField(default=False),
        ),
    ]
