# Generated by Django 6.0.4 on 2026-06-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_pago_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('en_proceso', 'En proceso'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
        migrations.AddField(
            model_name='pago',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Payment ID (MP)'),
        ),
        migrations.AddField(
            model_name='pago',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Preference ID (MP)'),
        ),
    ]
