# Generated by Django 6.0.4 on 2026-07-01 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pago_estado_pago_monto_pago_payment_id_and_more'),
        ('payments', '0003_pago_reembolsado'),
    ]

    operations = [
    ]
