# Generated by Django 6.0.4 on 2026-05-17 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('cupo', models.PositiveIntegerField(verbose_name='Cupo máximo')),
                ('actividad', models.CharField(choices=[('Tren inferior', 'Tren inferior'), ('Zona media', 'Zona media'), ('Tren superior', 'Tren superior')], max_length=20, verbose_name='Actividad')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('pago', 'Pago')], default='reservado', max_length=10, verbose_name='Estado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='classes.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'unique_together': {('id_usuario', 'id_turno')},
            },
        ),
        migrations.CreateModel(
            name='TurnoProfesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesionales', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesionales', to='classes.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Turno - Profesional',
                'verbose_name_plural': 'Turnos - Profesionales',
                'unique_together': {('id_turno', 'id_profesor')},
            },
        ),
    ]
