# Generated by Django 6.0.4 on 2026-05-18 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterModelOptions(
            name='turnoprofesional',
            options={},
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('pago', 'Pago'), ('lista_espera', 'Lista de espera')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='classes.turno'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnoprofesional',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesionales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turnoprofesional',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesionales', to='classes.turno'),
        ),
    ]
