# Generated by Django 6.0.4 on 2026-05-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_alter_reserva_options_alter_turnoprofesional_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
