# Generated by Django 6.0.4 on 2026-05-23 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_sala'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sala',
            options={'ordering': ['numero'], 'verbose_name': 'Sala', 'verbose_name_plural': 'Salas'},
        ),
        migrations.AlterField(
            model_name='turno',
            name='actividad',
            field=models.CharField(choices=[('tren_inferior', 'Tren inferior'), ('zona_media', 'Zona media'), ('tren_superior', 'Tren superior')], max_length=20, verbose_name='Actividad'),
        ),
        migrations.AlterField(
            model_name='turnoprofesional',
            name='id_profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesionales', to='professor.profesor'),
        ),
    ]
