# Generated by Django 6.0.4 on 2026-05-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_sala_options_alter_turno_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='classes.sala'),
            preserve_default=False,
        ),
    ]
