# Generated by Django 6.0.4 on 2026-05-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_reserva_recepcionado'),
        ('classes', '0004_alter_sala_options_alter_turno_actividad_and_more'),
    ]

    operations = [
    ]
