# Generated by Django 6.0.4 on 2026-05-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_turno_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio'),
        ),
    ]
