# Generated by Django 6.0.4 on 2026-05-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_merge_20260524_1856'),
        ('classes', '0006_turno_precio'),
    ]

    operations = [
    ]
