# Generated by Django 6.0.4 on 2026-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_certificadomedico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadomedico',
            name='imagen',
            field=models.ImageField(upload_to='certificados_medicos/%Y/%m/', verbose_name='Imagen O PDF del certificado'),
        ),
    ]
