# Generated by Django 6.0.4 on 2026-06-18 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_alter_reserva_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='unique_active_reserva_per_user_and_turno',
        ),
    ]
