# Generated by Django 6.0.4 on 2026-06-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_reserva_qr_token'),
        ('classes', '0011_remove_reserva_unique_active_reserva_per_user_and_turno'),
    ]

    operations = [
    ]
