# Generated by Django 6.0.4 on 2026-06-30 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_merge_20260630_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Token de QR'),
        ),
    ]
