# Generated by Django 6.0.4 on 2026-07-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_alter_reserva_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('cancelado', 'Cancelado'), ('pago', 'Pago'), ('lista_espera', 'Lista de espera'), ('devolver_dinero', 'Devolver dinero'), ('dinero_devuelto', 'Dinero devuelto')], default='reservado', max_length=15),
        ),
    ]
