# Generated by Django 6.0.4 on 2026-07-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
